"""Trim non-freight rail and waterways; gate water connectors on real ports.

Findings (18 Sep 2026, user-spotted on the flow map): the OSM extraction let
non-freight infrastructure into the network, and multimodal connectors were
auto-generated by road/water proximity rather than at documented terminals.
Flows exploited both: 146 kt/week barged up the (dammed) Olt, 69 kt/week up
the non-navigable Siret, and Sulina traffic sneaked down the littoral cordon
canal to dodge the waterway->maritime transfer.

Actions (domestic layers only; TEN-T and UAMD: rows untouched):
  railways   drop heritage/tourism and narrow-gauge lines
             (Mocanita Brad-Criscior, CFI Fieni-Moroeni)
  waterways  keep only the freight system by name whitelist: Danube mainstem
             (all spellings), navigable arms (Chilia, Sulina, Tulcea, Macin,
             Borcea, Bala), Danube-Black Sea + Poarta Alba-Midia-Navodari
             canals, harbour basins; drop tributaries (Olt, Siret, Vedea,
             Cerna, Arges, BG/RS side rivers...), delta creeks, cordon canal.
             Unnamed braided side-channels are dropped, then re-added one by
             one only where they reconnect the kept network.
  multimodal drop domestic *-waterways connectors farther than PORT_RADIUS_KM
             from a documented port (28 of 66) - barge access only at ports.

Backups: transport_pre_trim.gpkg / multimodal_pre_trim.gpkg (first run only).
Run in the dsc env: python romania_trim_network.py
"""

from __future__ import annotations

import math
import re
import shutil
from pathlib import Path

import geopandas as gpd
import networkx as nx

T = Path(r"C:/Users/Celian/OneDrive/DisruptSC/disrupt-sc-data/Romania/Transport")
GPKG, MM = T / "transport.gpkg", T / "multimodal.gpkg"

WATER_KEEP = re.compile(
    "dun|дун|danube|кілійське|chilia|sulina|tulcea|m[aă]cin|borcea|bala"
    "|marea neagr|poarta alb|midia|n[aă]vodari|harbour|UAMD:", re.IGNORECASE)

RAIL_DROP_USAGE = re.compile("tourism|heritage", re.IGNORECASE)
RAIL_NARROW = re.compile(r"^(760|610|1000)$|; ?760")

PORT_RADIUS_KM = 10.0
PORTS = {
    "Constanta": (28.65, 44.10), "Midia": (28.68, 44.32), "Galati": (28.03, 45.43),
    "Braila": (27.97, 45.27), "Tulcea": (28.80, 45.18), "Sulina": (29.65, 45.16),
    "Isaccea": (28.46, 45.27), "Macin": (28.13, 45.25), "Cernavoda": (28.03, 44.34),
    "Medgidia": (28.27, 44.24), "Basarabi": (28.40, 44.18), "Ovidiu": (28.57, 44.26),
    "Harsova": (27.95, 44.68), "Fetesti": (27.83, 44.38), "Calarasi": (27.31, 44.19),
    "Oltenita": (26.64, 44.08), "Giurgiu": (25.97, 43.89), "Zimnicea": (25.37, 43.64),
    "TurnuMagurele": (24.87, 43.72), "Corabia": (24.50, 43.76), "Bechet": (23.94, 43.76),
    "Calafat": (22.93, 43.99), "Drobeta": (22.66, 44.62), "Orsova": (22.40, 44.72),
    "MoldovaVeche": (21.66, 44.72), "Reni": (28.28, 45.46), "Izmail": (28.83, 45.33),
    "Giurgiulesti": (28.20, 45.47),
}


def hav_km(a, b):
    lo1, la1, lo2, la2 = map(math.radians, [a[0], a[1], b[0], b[1]])
    return 6371 * 2 * math.asin(math.sqrt(
        math.sin((la2 - la1) / 2) ** 2
        + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2))


def ends(geom):
    cs = list(geom.coords)
    return (round(cs[0][0], 6), round(cs[0][1], 6)), (round(cs[-1][0], 6), round(cs[-1][1], 6))


def main():
    for src, bak in [(GPKG, T / "transport_pre_trim.gpkg"), (MM, T / "multimodal_pre_trim.gpkg")]:
        if not bak.exists():
            shutil.copy2(src, bak)
            print(f"backup: {bak.name}")

    # ---- railways --------------------------------------------------------
    rl = gpd.read_file(GPKG, layer="railways")
    dom = rl["foreign"].fillna(0) != 1
    drop = dom & (rl["usage"].astype(str).str.contains(RAIL_DROP_USAGE, na=False)
                  | rl["gauge"].astype(str).str.match(RAIL_NARROW, na=False))
    for _, r in rl[drop].iterrows():
        print(f"rail drop: {str(r['name'])[:50]} ({r['km']:.0f} km, usage={r['usage']}, gauge={r['gauge']})")
    rl = rl[~drop].reset_index(drop=True)
    rl.to_file(GPKG, layer="railways", driver="GPKG")
    print(f"railways: -{drop.sum()} edges")

    # ---- waterways -------------------------------------------------------
    ww = gpd.read_file(GPKG, layer="waterways")
    dom = ww["foreign"].fillna(0) != 1
    named_keep = ww["name"].astype(str).str.contains(WATER_KEEP, na=False)
    unnamed = ww["name"].isna() | (ww["name"].astype(str).str.strip().isin(("", "None", "nan")))
    keep = ~dom | named_keep          # foreign rows and whitelisted names stay
    dropped_named = int((dom & ~named_keep & ~unnamed).sum())
    dropped_unnamed_idx = ww.index[dom & unnamed]

    # connectivity repair: re-add unnamed side-channels only where they
    # reconnect two components of the kept waterway graph
    G = nx.Graph()
    for _, r in ww[keep].iterrows():
        a, b = ends(r.geometry)
        G.add_edge(a, b)
    readded = 0
    changed = True
    while changed:
        changed = False
        for i in dropped_unnamed_idx:
            if keep.loc[i]:
                continue
            a, b = ends(ww.loc[i].geometry)
            if a in G and b in G and nx.has_path(G, a, b):
                continue
            if a in G and b in G:      # joins two existing components
                G.add_edge(a, b)
                keep.loc[i] = True
                readded += 1
                changed = True
    ww2 = ww[keep].reset_index(drop=True)
    ww2.to_file(GPKG, layer="waterways", driver="GPKG")
    n_drop = len(ww) - len(ww2)
    print(f"waterways: -{n_drop} edges ({dropped_named} named tributaries/creeks, "
          f"{len(dropped_unnamed_idx) - readded} unnamed side-channels; {readded} unnamed re-added for connectivity)")
    comps = sorted((len(c) for c in nx.connected_components(G)), reverse=True)
    print(f"kept waterway graph components: {comps[:5]}")

    # ---- multimodal: port-gate domestic water connectors -----------------
    mm = gpd.read_file(MM)
    is_water = mm["multimodes"].astype(str).str.contains("waterways")
    dom = mm["foreign"].fillna(0) != 1
    cent = mm.geometry.centroid
    too_far = [
        i for i in mm.index[is_water & dom]
        if min(hav_km((cent[i].x, cent[i].y), p) for p in PORTS.values()) > PORT_RADIUS_KM
    ]
    mm2 = mm.drop(index=too_far).reset_index(drop=True)
    mm2.to_file(MM, layer="multimodal", driver="GPKG")
    print(f"multimodal: -{len(too_far)} domestic waterway connectors beyond "
          f"{PORT_RADIUS_KM:.0f} km of a documented port "
          f"({int((is_water & dom).sum()) - len(too_far)} port connectors kept)")


if __name__ == "__main__":
    main()
